export const ADD_TASK = {
  STARTED: "ADD_TASK_STARTED",
  SUCCESS: "ADD_TASK_SUCCESS",
  FAILED: "ADD_TASK_FAILED",
};

export const REMOVE_TASK = {
  STARTED: "REMOVE_TASK_STARTED",
  SUCCESS: "REMOVE_TASK_SUCCESS",
  FAILED: "REMOVE_TASK_FAILED",
};

export const EDIT_TASK = {
  STARTED: "EDIT_TASK_STARTED",
  SUCCESS: "EDIT_TASK_SUCCESS",
  FAILED: "EDIT_TASK_FAILED",
};

export const TOGGLE_TASK = {
  STARTED: "TOGGLE_TASK_STARTED",
  SUCCESS: "TOGGLE_TASK_SUCCESS",
  FAILED: "TOGGLE_TASK_FAILED",
};

export const FETCH_TASKS = {
  STARTED: "FETCH_TASKS_STARTED",
  SUCCESS: "FETCH_TASKS_SUCCESS",
  FAILED: "FETCH_TASKS_FAILED",
};
