export const USER_REGISTER = {
  STARTED: "USER_REGISTER_STARTED",
  SUCCESS: "USER_REGISTER_SUCCESS",
  FAILED: "USER_REGISTER_FAILED",
};

export const USER_LOGIN = {
  STARTED: "USER_LOGIN_STARTED",
  SUCCESS: "USER_LOGIN_SUCCESS",
  FAILED: "USER_LOGIN_FAILED",
};

export const USER_LOGOUT = {
  STARTED: "USER_LOGOUT_STARTED",
  SUCCESS: "USER_LOGOUT_SUCCESS",
  FAILED: "USER_LOGOUT_FAILED",
};
